@echo off
rem Clean up any existing node processes
echo Stopping existing processes...
> nul
echo Cleaning database...
del /s /q "%cd%\orchestrator\data\jobs.db*" 2>nul
echo Rebuilding database dependencies...
npm --workspace orchestrator rebuild better-sqlite3
echo Database rebuilt.
echo Starting JobOps server...
cd "%cd%\orchestrator"
npm --workspace orchestrator run dev:server
